### ISSUE TITLE
May I have a credit?

### ISSUE THREAD

**Issue by JLChnToZ** [mrnamwen/IIDXCustomMix#1]
Hi, I have been notified that you have used the pre-built [Bemusilization](https://github.com/JLChnToZ/Bemusilization) library in this repository. According to [the license](https://github.com/JLChnToZ/Bemusilization/blob/master/LICENSE), you have to make a credit and provide instructions to obtain the source (which can be just a link back), so I hope you can add them back, thanks.

**Comment by mrnamwen** [comment]
Sure thing, I'll add it in the next commit. Didn't intend to use your library full-time in the beginning and wanted to write my own, but it appears that yours covers the use case I need.

**Comment by JLChnToZ** [comment]
Okay, thank you very much :simple_smile:

**Comment by mrnamwen** [comment]
>discord emotes on github
